In [1]:
import pandas as pd
import numpy as np
import requests
from pandas.io.json import json_normalize
import json
import csv

In [47]:
pd.set_option("display.max_rows", None, "display.max_columns", None)

In [2]:
url ='https://fantasy.premierleague.com/api/leagues-classic/1771282/standings/'
r = requests.get(url).text
json_data = json.loads(r)
# print (json.dumps(json_data, indent=2))

In [3]:
#converting to csv

In [4]:
data = pd.DataFrame(json_data['standings']['results'])
data.to_csv('nuno_league_standings.csv', index=False)

In [5]:
data

,id,event_total,player_name,rank,last_rank,rank_sort,total,entry,entry_name
0,47078855,0,shareque zaman,1,1,1,371,7514332,Pandaking17
1,47022839,0,Mahbube Rabbani,2,2,2,357,7506093,Timo Werner
2,46955303,0,Mubtasim Fuad,3,3,3,347,7495685,Iron Man
3,47021198,0,Saraf Hasan,4,4,4,346,7504874,Chotpoti FC
4,47021570,0,Tasnimul Hasan,5,5,5,343,7505919,Lithium FC
5,46953199,0,Tauhid Sefo,6,6,6,336,6455623,Chelseaismylife
6,46955284,0,Pial Rahman,7,7,7,329,7496007,বুঝো নাই ব্যাপারটা?
7,46950510,0,Abrar Hossain,8,8,8,327,7495061,Allison Wonderland
8,46951141,0,Likhon Amin,9,9,9,318,6455571,Kalojaam
9,46952114,0,Mahedur Rahman,10,10,10,304,6455293,Armaggeeddhon
10,47027899,0,Asif Bin Zaman,11,11,11,302,7506788,Fred the Red
11,46953007,0,Zabir Sami,12,12,12,291,7495692,MUSHTAQ
12,46971910,0,Muntasir Azad,13,13,13,289,6455462,Shadowr Team

In [6]:
url ='https://fantasy.premierleague.com/api/entry/7514332/history/'
t = requests.get(url).text
json_data = json.loads(t)
# print (json.dumps(json_data, indent=2))

In [7]:
data_t = pd.DataFrame(json_data['current'])
data_t.to_csv('nuno_league_standings.csv', index=False)

In [8]:
data_t

,event,points,total_points,rank,rank_sort,overall_rank,bank,value,event_transfers,event_transfers_cost,points_on_bench
0,39,95,95,516166.0,531669.0,7438385,0,1000,0,0,3
1,40,69,164,2559548.0,2577701.0,7434563,4,1002,1,0,1
2,41,96,260,38262.0,41791.0,7411604,4,1004,0,0,6
3,42,51,311,3510090.0,3525464.0,7410287,14,1004,2,0,4
4,43,60,371,3706077.0,3720537.0,7407954,4,1005,1,0,2
5,44,0,371,NaN,NaN,7407954,20,1007,2,4,0

In [54]:
result = []
team_id = data['entry'].tolist()

for team in team_id:
    url_tid = 'https://fantasy.premierleague.com/api/entry/' + str(team) + '/history/'
    p_id = requests.get(url_tid).text
    json_data_p_id = json.loads(p_id)
#     print(json.dumps(json_data_p, indent =2))  #prints JSON for every player
    for x in range(len(json_data_p_id['current'])):
        row = [team, 
               json_data_p_id['current'][x]['event'], 
               json_data_p_id['current'][x]['points'],
               json_data_p_id['current'][x]['total_points'],
               json_data_p_id['current'][x]['value'], 
               json_data_p_id['current'][x]['event_transfers'],
               json_data_p_id['current'][x]['points_on_bench']]
        result.append(row)

In [10]:
result

[[7514332, 39, 95, 95, 1000, 0, 3],
 [7514332, 40, 69, 164, 1002, 1, 1],
 [7514332, 41, 96, 260, 1004, 0, 6],
 [7514332, 42, 51, 311, 1004, 2, 4],
 [7514332, 43, 60, 371, 1005, 1, 2],
 [7514332, 44, 0, 371, 1007, 2, 0],
 [7506093, 39, 61, 61, 1000, 0, 0],
 [7506093, 40, 63, 124, 1000, 0, 3],
 [7506093, 41, 63, 187, 1003, 2, 2],
 [7506093, 42, 76, 259, 1002, 2, 2],
 [7506093, 43, 98, 357, 1008, 1, 7],
 [7506093, 44, 0, 357, 1010, 0, 0],
 [7495685, 39, 69, 69, 1000, 0, 2],
 [7495685, 40, 72, 137, 1001, 2, 1],
 [7495685, 41, 93, 230, 1008, 1, 2],
 [7495685, 42, 60, 286, 1010, 2, 0],
 [7495685, 43, 65, 347, 1015, 2, 2],
 [7495685, 44, 0, 347, 1019, 2, 0],
 [7504874, 39, 72, 72, 1000, 0, 12],
 [7504874, 40, 63, 135, 1001, 1, 5],
 [7504874, 41, 85, 220, 1000, 0, 3],
 [7504874, 42, 68, 288, 996, 2, 2],
 [7504874, 43, 58, 346, 1000, 1, 0],
 [7504874, 44, 0, 346, 1001, 1, 0],
 [7505919, 39, 59, 59, 1000, 0, 12],
 [7505919, 40, 59, 114, 1000, 2, 8],
 [7505919, 41, 85, 199, 1001, 1, 3],
 [7505919, 42, 60, 259, 1001, 1, 0],
 [7505919, 43, 84, 343, 1001, 1, -2],
 [7505919, 44, 0, 343, 999, 1, 0],
 [6455623, 4, 50, 50, 1006, 0, 5],
 [6455623, 5, 57, 87, 1008, 6, 13],
 [6455623, 6, 70, 157, 1012, 0, 14],
 [6455623, 7, 41, 198, 1014, 2, 4],
 [6455623, 8, 37, 235, 1015, 1, 2],
 [6455623, 9, 30, 265, 1018, 1, 0],
 [6455623, 10, 32, 297, 1017, 0, -1],
 [6455623, 11, 62, 359, 1014, 0, 0],
 [6455623, 12, 44, 403, 1008, 0, 0],
 [6455623, 13, 68, 471, 1002, 0, 0],
 [6455623, 14, 34, 505, 999, 0, 1],
 [6455623, 15, 42, 547, 999, 0, 0],
 [6455623, 16, 48, 595, 999, 0, 0],
 [6455623, 17, 67, 662, 1002, 0, 7],
 [6455623, 18, 35, 697, 1007, 0, 1],
 [6455623, 19, 53, 750, 1005, 0, 0],
 [6455623, 20, 42, 792, 1003, 0, 0],
 [6455623, 21, 39, 831, 1004, 0, -1],
 [6455623, 22, 53, 884, 1005, 0, 0],
 [6455623, 23, 46, 930, 1002, 1, 1],
 [6455623, 24, 60, 990, 1001, 0, 1],
 [6455623, 25, 41, 1031, 1001, 0, 0],
 [6455623, 26, 59, 1090, 1002, 0, 0],
 [6455623, 27, 64, 1154, 997, 0, 1],
 [6455623, 28, 36, 1190, 999, 0, 0],
 [6455623, 29, 58, 1248, 1001, 0, 2],
 [6455623, 30, 0, 1248, 1001, 0, 0],
 [6455623, 31, 0, 1248, 1001, 0, 0],
 [6455623, 32, 0, 1248, 1004, 0, 0],
 [6455623, 33, 0, 1248, 1006, 0, 0],
 [6455623, 34, 0, 1248, 1006, 0, 0],
 [6455623, 35, 0, 1248, 1006, 0, 0],
 [6455623, 36, 0, 1248, 1006, 0, 0],
 [6455623, 37, 0, 1248, 1006, 0, 0],
 [6455623, 38, 0, 1248, 1006, 0, 0],
 [6455623, 39, 66, 1314, 990, 26, 2],
 [6455623, 40, 74, 1388, 992, 1, 3],
 [6455623, 41, 56, 1444, 994, 1, 7],
 [6455623, 42, 75, 1515, 994, 2, 3],
 [6455623, 43, 69, 1584, 995, 1, 0],
 [6455623, 44, 0, 1584, 994, 2, 0],
 [7496007, 39, 92, 92, 1000, 0, 8],
 [7496007, 40, 56, 148, 1002, 1, -1],
 [7496007, 41, 61, 209, 1004, 1, 3],
 [7496007, 42, 54, 259, 1008, 2, 7],
 [7496007, 43, 70, 329, 1011, 1, -1],
 [7496007, 44, 0, 329, 1011, 3, 0],
 [7495061, 39, 56, 56, 1000, 0, 9],
 [7495061, 40, 73, 125, 1002, 2, 2],
 [7495061, 41, 98, 223, 1007, 1, 3],
 [7495061, 42, 54, 277, 1011, 1, 7],
 [7495061, 43, 54, 327, 1015, 2, 2],
 [7495061, 44, 0, 327, 1015, 5, 0],
 [6455571, 4, 59, 59, 1002, 0, 5],
 [6455571, 5, 61, 100, 1008, 6, 6],
 [6455571, 6, 65, 165, 1010, 0, 5],
 [6455571, 7, 44, 209, 1013, 2, 6],
 [6455571, 8, 43, 252, 1013, 1, 6],
 [6455571, 9, 29, 281, 1015, 1, 8],
 [6455571, 10, 46, 327, 1014, 0, 7],
 [6455571, 11, 60, 387, 1015, 0, 9],
 [6455571, 12, 55, 442, 1014, 0, 1],
 [6455571, 13, 54, 496, 1013, 0, 0],
 [6455571, 14, 75, 571, 1010, 0, 0],
 [6455571, 15, 52, 623, 1010, 0, 9],
 [6455571, 16, 61, 684, 1013, 0, 2],
 [6455571, 17, 57, 741, 1013, 0, 0],
 [6455571, 18, 22, 763, 1011, 0, 0],
 [6455571, 19, 54, 817, 1008, 0, 0],
 [6455571, 20, 47, 864, 1006, 0, 0],
 [6455571, 21, 47, 911, 1005, 0, 1],
 [6455571, 22, 41, 952, 1006, 0, 0],
 [6455571, 23, 57, 1009, 1003, 0, 1],
 [6455571, 24, 73, 1082, 1004, 0, 0],
 [6455571, 25, 58, 1140, 1003, 0, 9],
 [6455571, 26, 58, 1198, 1008, 0, 2],
 [6455571, 27, 77, 1275, 1008, 0, 0],
 [6455571, 28, 32, 1307, 1008, 0, 0],
 [6455571, 29, 41, 1348, 1008, 0, 0],
 [6455571, 30, 0, 1348, 1009, 0, 0],
 [6455571, 31, 0, 1348, 1009, 0, 0],
 [6455571, 32, 0, 1348, 1008, 0, 0],
 [6455571, 33, 0, 1348, 1009, 0, 0],
 [6455571, 34, 0, 1348, 1009, 0, 0],
 [6455571, 35, 0, 1348, 1009, 0, 0],
 [6455571, 36, 0, 1348, 1009, 0, 0],
 [6455571, 37, 0, 1348, 1009, 0, 0],
 [6455571, 38, 0, 1348, 1009, 0, 0],
 [6455571, 39, 64, 1412, 1000, 24, 1],
 [6455571, 40, 53, 1461, 1001, 2, 3],
 [6455571, 41, 77, 1538, 1003, 1, 9],
 [6455571, 42, 63, 1593, 1005, 3, 4],
 [6455571, 43, 81, 1666, 1006, 3, 0],
 [6455571, 44, 0, 1666, 1007, 2, 0],
 [6455293, 4, 52, 52, 1004, 0, 6],
 [6455293, 5, 40, 52, 1007, 11, 3],
 [6455293, 6, 75, 127, 1008, 0, 4],
 [6455293, 7, 50, 177, 1010, 1, 4],
 [6455293, 8, 39, 216, 1011, 2, 5],
 [6455293, 9, 30, 246, 1014, 0, 9],
 [6455293, 10, 33, 279, 1014, 0, 0],
 [6455293, 11, 63, 342, 1011, 0, 0],
 [6455293, 12, 47, 389, 1010, 0, 0],
 [6455293, 13, 50, 439, 1009, 0, 0],
 [6455293, 14, 74, 513, 1004, 0, 8],
 [6455293, 15, 55, 568, 1009, 0, 2],
 [6455293, 16, 53, 621, 1018, 0, 0],
 [6455293, 17, 65, 686, 1020, 0, 0],
 [6455293, 18, 56, 738, 1019, 3, 0],
 [6455293, 19, 35, 765, 1019, 3, 2],
 [6455293, 20, 65, 830, 1021, 0, 0],
 [6455293, 21, 54, 864, 1021, 7, 5],
 [6455293, 22, 56, 920, 1023, 0, 6],
 [6455293, 23, 30, 950, 1029, 0, 15],
 [6455293, 24, 42, 992, 1029, 2, 7],
 [6455293, 25, 37, 1029, 1030, 0, 0],
 [6455293, 26, 63, 1092, 1028, 2, 8],
 [6455293, 27, 61, 1153, 1027, 0, 2],
 [6455293, 28, 24, 1177, 1027, 0, 0],
 [6455293, 29, 66, 1243, 1024, 0, 1],
 [6455293, 30, 0, 1243, 1021, 0, 0],
 [6455293, 31, 0, 1243, 1021, 0, 0],
 [6455293, 32, 0, 1243, 1019, 0, 0],
 [6455293, 33, 0, 1243, 1021, 0, 0],
 [6455293, 34, 0, 1243, 1021, 0, 0],
 [6455293, 35, 0, 1243, 1021, 0, 0],
 [6455293, 36, 0, 1243, 1021, 0, 0],
 [6455293, 37, 0, 1243, 1021, 0, 0],
 [6455293, 38, 0, 1243, 1021, 0, 0],
 [6455293, 39, 77, 1320, 1003, 21, 2],
 [6455293, 40, 74, 1394, 1004, 1, 2],
 [6455293, 41, 53, 1447, 1008, 1, 3],
 [6455293, 42, 46, 1489, 1009, 2, 2],
 [6455293, 43, 62, 1547, 1012, 2, 0],
 [6455293, 44, 0, 1547, 1012, 1, 0],
 [7506788, 39, 61, 61, 1000, 0, 1],
 [7506788, 40, 60, 113, 1002, 3, 4],
 [7506788, 41, 49, 162, 1004, 1, 7],
 [7506788, 42, 70, 228, 1004, 2, 4],
 [7506788, 43, 82, 302, 1006, 3, 2],
 [7506788, 44, 0, 302, 1009, 1, 0],
 [7495692, 39, 73, 73, 1000, 0, 10],
 [7495692, 40, 75, 148, 1002, 1, 9],
 [7495692, 41, 36, 184, 1005, 1, 3],
 [7495692, 42, 60, 240, 1006, 2, 2],
 [7495692, 43, 55, 291, 1009, 2, 1],
 [7495692, 44, 0, 291, 1010, 3, 0],
 [6455462, 4, 52, 52, 1003, 0, 0],
 [6455462, 5, 40, 84, 1005, 3, 11],
 [6455462, 6, 76, 160, 1008, 0, 0],
 [6455462, 7, 49, 209, 1010, 2, 6],
 [6455462, 8, 32, 237, 1014, 2, 9],
 [6455462, 9, 29, 266, 1015, 0, 11],
 [6455462, 10, 46, 312, 1015, 0, 1],
 [6455462, 11, 33, 345, 1012, 0, 7],
 [6455462, 12, 41, 386, 1009, 0, 2],
 [6455462, 13, 61, 447, 1006, 0, 10],
 [6455462, 14, 55, 502, 1007, 0, 1],
 [6455462, 15, 73, 575, 1010, 0, 20],
 [6455462, 16, 72, 647, 1019, 0, 2],
 [6455462, 17, 65, 712, 1022, 0, 7],
 [6455462, 18, 64, 776, 1026, 0, 3],
 [6455462, 19, 28, 804, 1026, 0, 2],
 [6455462, 20, 56, 860, 1026, 0, 0],
 [6455462, 21, 61, 905, 1024, 6, 1],
 [6455462, 22, 55, 960, 1025, 0, 4],
 [6455462, 23, 30, 990, 1031, 0, 13],
 [6455462, 24, 33, 1023, 1031, 0, 11],
 [6455462, 25, 27, 1050, 1028, 0, 0],
 [6455462, 26, 64, 1114, 1025, 0, 2],
 [6455462, 27, 51, 1165, 1022, 0, 1],
 [6455462, 28, 18, 1183, 1023, 0, 0],
 [6455462, 29, 78, 1261, 1021, 0, 0],
 [6455462, 30, 0, 1261, 1018, 0, 0],
 [6455462, 31, 0, 1261, 1018, 0, 0],
 [6455462, 32, 0, 1261, 1018, 0, 0],
 [6455462, 33, 0, 1261, 1018, 0, 0],
 [6455462, 34, 0, 1261, 1018, 0, 0],
 [6455462, 35, 0, 1261, 1018, 0, 0],
 [6455462, 36, 0, 1261, 1018, 0, 0],
 [6455462, 37, 0, 1261, 1018, 0, 0],
 [6455462, 38, 0, 1261, 1018, 0, 0],
 [6455462, 39, 55, 1316, 1009, 7, 2],
 [6455462, 40, 66, 1382, 1004, 1, 8],
 [6455462, 41, 55, 1437, 1005, 1, 2],
 [6455462, 42, 61, 1494, 1006, 2, 17],
 [6455462, 43, 60, 1550, 1010, 2, 19],
 [6455462, 44, 0, 1550, 1009, 3, 0]]

In [55]:
player_df = pd.DataFrame(result, columns= ['Team ID','GW', 'Points','Total Points','Sqaud Value', 'Transfers in GW', 'Points on Bench'])

In [51]:
player_df

,Team ID,GW,Points,Total Points,Sqaud Value,Transfers in GW,Points on Bench
0,7514332,39,95,95,1000,0,3
1,7514332,40,69,164,1002,1,1
2,7514332,41,96,260,1004,0,6
3,7514332,42,51,311,1004,2,4
4,7514332,43,60,371,1005,1,2
5,7514332,44,0,371,1007,2,0
6,7506093,39,61,61,1000,0,0
7,7506093,40,63,124,1000,0,3
8,7506093,41,63,187,1003,2,2
9,7506093,42,76,259,1002,2,2
10,7506093,43,98,357,1008,1,7
11,7506093,44,0,357,1010,0,0
12,7495685,39,69,69,1000,0,2
13,7495685,40,72,137,1001,2,1
14,7495685,41,93,230,1008,1,2
15,7495685,42,60,286,1010,2,0
16,7495685,43,65,347,1015,2,2
17,7495685,44,0,347,1019,2,0
18,7504874,39,72,72,1000,0,12
19,7504874,40,63,135,1001,1,5
20,7504874,41,85,220,1000,0,3
21,7504874,42,68,288,996,2,2
22,7504874,43,58,346,1000,1,0
23,7504874,44,0,346,1001,1,0
24,7505919,39,59,59,1000,0,12
25,7505919,40,59,114,1000,2,8
26,7505919,41,85,199,1001,1,3
27,7505919,42,60,259,1001,1,0
28,7505919,43,84,343,1001,1,-2
29,7505919,44,0,343,999,1,0
30,6455623,4,50,50,1006,0,5
31,6455623,5,57,87,1008,6,13
32,6455623,6,70,157,1012,0,14
33,6455623,7,41,198,1014,2,4
34,6455623,8,37,235,1015,1,2
35,6455623,9,30,265,1018,1,0
36,6455623,10,32,297,1017,0,-1
37,6455623,11,62,359,1014,0,0
38,6455623,12,44,403,1008,0,0
39,6455623,13,68,471,1002,0,0
40,6455623,14,34,505,999,0,1
41,6455623,15,42,547,999,0,0
42,6455623,16,48,595,999,0,0
43,6455623,17,67,662,1002,0,7
44,6455623,18,35,697,1007,0,1
45,6455623,19,53,750,1005,0,0
46,6455623,20,42,792,1003,0,0
47,6455623,21,39,831,1004,0,-1
48,6455623,22,53,884,1005,0,0
49,6455623,23,46,930,1002,1,1
50,6455623,24,60,990,1001,0,1
51,6455623,25,41,1031,1001,0,0
52,6455623,26,59,1090,1002,0,0
53,6455623,27,64,1154,997,0,1
54,6455623,28,36,1190,999,0,0
55,6455623,29,58,1248,1001,0,2
56,6455623,30,0,1248,1001,0,0
57,6455623,31,0,1248,1001,0,0
58,6455623,32,0,1248,1004,0,0
59,6455623,33,0,1248,1006,0,0
60,6455623,34,0,1248,1006,0,0
61,6455623,35,0,1248,1006,0,0
62,6455623,36,0,1248,1006,0,0
63,6455623,37,0,1248,1006,0,0
64,6455623,38,0,1248,1006,0,0
65,6455623,39,66,1314,990,26,2
66,6455623,40,74,1388,992,1,3
67,6455623,41,56,1444,994,1,7
68,6455623,42,75,1515,994,2,3
69,6455623,43,69,1584,995,1,0
70,6455623,44,0,1584,994,2,0
71,7496007,39,92,92,1000,0,8
72,7496007,40,56,148,1002,1,-1
73,7496007,41,61,209,1004,1,3
74,7496007,42,54,259,1008,2,7
75,7496007,43,70,329,1011,1,-1
76,7496007,44,0,329,1011,3,0
77,7495061,39,56,56,1000,0,9
78,7495061,40,73,125,1002,2,2
79,7495061,41,98,223,1007,1,3
80,7495061,42,54,277,1011,1,7
81,7495061,43,54,327,1015,2,2
82,7495061,44,0,327,1015,5,0
83,6455571,4,59,59,1002,0,5
84,6455571,5,61,100,1008,6,6
85,6455571,6,65,165,1010,0,5
86,6455571,7,44,209,1013,2,6
87,6455571,8,43,252,1013,1,6
88,6455571,9,29,281,1015,1,8
89,6455571,10,46,327,1014,0,7
90,6455571,11,60,387,1015,0,9
91,6455571,12,55,442,1014,0,1
92,6455571,13,54,496,1013,0,0
93,6455571,14,75,571,1010,0,0
94,6455571,15,52,623,1010,0,9
95,6455571,16,61,684,1013,0,2
96,6455571,17,57,741,1013,0,0
97,6455571,18,22,763,1011,0,0
98,6455571,19,54,817,1008,0,0
99,6455571,20,47,864,1006,0,0
100,6455571,21,47,911,1005,0,1
101,6455571,22,41,952,1006,0,0
102,6455571,23,57,1009,1003,0,1
103,6455571,24,73,1082,1004,0,0
104,6455571,25,58,1140,1003,0,9
105,6455571,26,58,1198,1008,0,2
106,6455571,27,77,1275,1008,0,0
107,6455571,28,32,1307,1008,0,0
108,6455571,29,41,1348,1008,0,0
109,6455571,30,0,1348,1009,0,0
110,6455571,31,0,1348,1009,0,0
111,6455571,32,0,1348,1008,0,0
112,6455571,33,0,1348,1009,0,0
113,6455571,34,0,1348,1009,0,0
114,6455571,35,0,1348,1009,0,0
115,6455571,36,0,1348,1009,0,0
116,6455571,37,0,1348,1009,0,0
117,6455571,38,0,1348,1009,0,0
118,6455571,39,64,1412,1000,24,1
119,6455571,40,53,1461,1001,2,3
120,6455571,41,77,1538,1003,1,9
121,6455571,42,63,1593,1005,3,4
122,6455571,43,81,1666,1006,3,0
123,6455571,44,0,1666,1007,2,0
124,6455293,4,52,52,1004,0,6
125,6455293,5,40,52,1007,11,3
126,6455293,6,75,127,1008,0,4
127,6455293,7,50,177,1010,1,4
128,6455293,8,39,216,1011,2,5
129,6455293,9,30,246,1014,0,9
130,6455293,10,33,279,1014,0,0
131,6455293,11,63,342,1011,0,0
132,6455293,12,47,389,1010,0,0
133,6455293,13,50,439,1009,0,0
134,6455293,14,74,513,1004,0,8
135,6455293,15,55,568,1009,0,2
136,6455293,16,53,621,1018,0,0
137,6455293,17,65,686,1020,0,0
138,6455293,18,56,738,1019,3,0
139,6455293,19,35,765,1019,3,2
140,6455293,20,65,830,1021,0,0
141,6455293,21,54,864,1021,7,5
142,6455293,22,56,920,1023,0,6
143,6455293,23,30,950,1029,0,15
144,6455293,24,42,992,1029,2,7
145,6455293,25,37,1029,1030,0,0
146,6455293,26,63,1092,1028,2,8
147,6455293,27,61,1153,1027,0,2
148,6455293,28,24,1177,1027,0,0
149,6455293,29,66,1243,1024,0,1
150,6455293,30,0,1243,1021,0,0
151,6455293,31,0,1243,1021,0,0
152,6455293,32,0,1243,1019,0,0
153,6455293,33,0,1243,1021,0,0
154,6455293,34,0,1243,1021,0,0
155,6455293,35,0,1243,1021,0,0
156,6455293,36,0,1243,1021,0,0
157,6455293,37,0,1243,1021,0,0
158,6455293,38,0,1243,1021,0,0
159,6455293,39,77,1320,1003,21,2
160,6455293,40,74,1394,1004,1,2
161,6455293,41,53,1447,1008,1,3
162,6455293,42,46,1489,1009,2,2
163,6455293,43,62,1547,1012,2,0
164,6455293,44,0,1547,1012,1,0
165,7506788,39,61,61,1000,0,1
166,7506788,40,60,113,1002,3,4
167,7506788,41,49,162,1004,1,7
168,7506788,42,70,228,1004,2,4
169,7506788,43,82,302,1006,3,2
170,7506788,44,0,302,1009,1,0
171,7495692,39,73,73,1000,0,10
172,7495692,40,75,148,1002,1,9
173,7495692,41,36,184,1005,1,3
174,7495692,42,60,240,1006,2,2
175,7495692,43,55,291,1009,2,1
176,7495692,44,0,291,1010,3,0
177,6455462,4,52,52,1003,0,0
178,6455462,5,40,84,1005,3,11
179,6455462,6,76,160,1008,0,0
180,6455462,7,49,209,1010,2,6
181,6455462,8,32,237,1014,2,9
182,6455462,9,29,266,1015,0,11
183,6455462,10,46,312,1015,0,1
184,6455462,11,33,345,1012,0,7
185,6455462,12,41,386,1009,0,2
186,6455462,13,61,447,1006,0,10
187,6455462,14,55,502,1007,0,1
188,6455462,15,73,575,1010,0,20
189,6455462,16,72,647,1019,0,2
190,6455462,17,65,712,1022,0,7
191,6455462,18,64,776,1026,0,3
192,6455462,19,28,804,1026,0,2
193,6455462,20,56,860,1026,0,0
194,6455462,21,61,905,1024,6,1
195,6455462,22,55,960,1025,0,4
196,6455462,23,30,990,1031,0,13
197,6455462,24,33,1023,1031,0,11
198,6455462,25,27,1050,1028,0,0
199,6455462,26,64,1114,1025,0,2
200,6455462,27,51,1165,1022,0,1
201,6455462,28,18,1183,1023,0,0
202,6455462,29,78,1261,1021,0,0
203,6455462,30,0,1261,1018,0,0
204,6455462,31,0,1261,1018,0,0
205,6455462,32,0,1261,1018,0,0
206,6455462,33,0,1261,1018,0,0
207,6455462,34,0,1261,1018,0,0
208,6455462,35,0,1261,1018,0,0
209,6455462,36,0,1261,1018,0,0
210,6455462,37,0,1261,1018,0,0
211,6455462,38,0,1261,1018,0,0
212,6455462,39,55,1316,1009,7,2
213,6455462,40,66,1382,1004,1,8
214,6455462,41,55,1437,1005,1,2
215,6455462,42,61,1494,1006,2,17
216,6455462,43,60,1550,1010,2,19
217,6455462,44,0,1550,1009,3,0

In [56]:
# df = df.drop(df[df.score < 50].index)
player_df =  player_df.drop(player_df[player_df.GW < 39].index)
player_df.loc[player_df['Total Points'] > 999, 'Total Points'] = 0
player_df

,Team ID,GW,Points,Total Points,Sqaud Value,Transfers in GW,Points on Bench
0,7514332,39,95,95,1000,0,3
1,7514332,40,69,164,1002,1,1
2,7514332,41,96,260,1004,0,6
3,7514332,42,51,311,1004,2,4
4,7514332,43,60,371,1005,1,2
5,7514332,44,0,371,1007,2,0
6,7506093,39,61,61,1000,0,0
7,7506093,40,63,124,1000,0,3
8,7506093,41,63,187,1003,2,2
9,7506093,42,76,259,1002,2,2
10,7506093,43,98,357,1008,1,7
11,7506093,44,0,357,1010,0,0
12,7495685,39,69,69,1000,0,2
13,7495685,40,72,137,1001,2,1
14,7495685,41,93,230,1008,1,2
15,7495685,42,60,286,1010,2,0
16,7495685,43,65,347,1015,2,2
17,7495685,44,0,347,1019,2,0
18,7504874,39,72,72,1000,0,12
19,7504874,40,63,135,1001,1,5
20,7504874,41,85,220,1000,0,3
21,7504874,42,68,288,996,2,2
22,7504874,43,58,346,1000,1,0
23,7504874,44,0,346,1001,1,0
24,7505919,39,59,59,1000,0,12
25,7505919,40,59,114,1000,2,8
26,7505919,41,85,199,1001,1,3
27,7505919,42,60,259,1001,1,0
28,7505919,43,84,343,1001,1,-2
29,7505919,44,0,343,999,1,0
65,6455623,39,66,0,990,26,2
66,6455623,40,74,0,992,1,3
67,6455623,41,56,0,994,1,7
68,6455623,42,75,0,994,2,3
69,6455623,43,69,0,995,1,0
70,6455623,44,0,0,994,2,0
71,7496007,39,92,92,1000,0,8
72,7496007,40,56,148,1002,1,-1
73,7496007,41,61,209,1004,1,3
74,7496007,42,54,259,1008,2,7
75,7496007,43,70,329,1011,1,-1
76,7496007,44,0,329,1011,3,0
77,7495061,39,56,56,1000,0,9
78,7495061,40,73,125,1002,2,2
79,7495061,41,98,223,1007,1,3
80,7495061,42,54,277,1011,1,7
81,7495061,43,54,327,1015,2,2
82,7495061,44,0,327,1015,5,0
118,6455571,39,64,0,1000,24,1
119,6455571,40,53,0,1001,2,3
120,6455571,41,77,0,1003,1,9
121,6455571,42,63,0,1005,3,4
122,6455571,43,81,0,1006,3,0
123,6455571,44,0,0,1007,2,0
159,6455293,39,77,0,1003,21,2
160,6455293,40,74,0,1004,1,2
161,6455293,41,53,0,1008,1,3
162,6455293,42,46,0,1009,2,2
163,6455293,43,62,0,1012,2,0
164,6455293,44,0,0,1012,1,0
165,7506788,39,61,61,1000,0,1
166,7506788,40,60,113,1002,3,4
167,7506788,41,49,162,1004,1,7
168,7506788,42,70,228,1004,2,4
169,7506788,43,82,302,1006,3,2
170,7506788,44,0,302,1009,1,0
171,7495692,39,73,73,1000,0,10
172,7495692,40,75,148,1002,1,9
173,7495692,41,36,184,1005,1,3
174,7495692,42,60,240,1006,2,2
175,7495692,43,55,291,1009,2,1
176,7495692,44,0,291,1010,3,0
212,6455462,39,55,0,1009,7,2
213,6455462,40,66,0,1004,1,8
214,6455462,41,55,0,1005,1,2
215,6455462,42,61,0,1006,2,17
216,6455462,43,60,0,1010,2,19
217,6455462,44,0,0,1009,3,0

In [52]:
player_df.loc[player_df['Total Points'] > 1000, 'First Season'] = 0

In [53]:
player_df

,Team ID,GW,Points,Total Points,Sqaud Value,Transfers in GW,Points on Bench,First Season
0,7514332,39,95,95,1000,0,3,NaN
1,7514332,40,69,164,1002,1,1,NaN
2,7514332,41,96,260,1004,0,6,NaN
3,7514332,42,51,311,1004,2,4,NaN
4,7514332,43,60,371,1005,1,2,NaN
5,7514332,44,0,371,1007,2,0,NaN
6,7506093,39,61,61,1000,0,0,NaN
7,7506093,40,63,124,1000,0,3,NaN
8,7506093,41,63,187,1003,2,2,NaN
9,7506093,42,76,259,1002,2,2,NaN
10,7506093,43,98,357,1008,1,7,NaN
11,7506093,44,0,357,1010,0,0,NaN
12,7495685,39,69,69,1000,0,2,NaN
13,7495685,40,72,137,1001,2,1,NaN
14,7495685,41,93,230,1008,1,2,NaN
15,7495685,42,60,286,1010,2,0,NaN
16,7495685,43,65,347,1015,2,2,NaN
17,7495685,44,0,347,1019,2,0,NaN
18,7504874,39,72,72,1000,0,12,NaN
19,7504874,40,63,135,1001,1,5,NaN
20,7504874,41,85,220,1000,0,3,NaN
21,7504874,42,68,288,996,2,2,NaN
22,7504874,43,58,346,1000,1,0,NaN
23,7504874,44,0,346,1001,1,0,NaN
24,7505919,39,59,59,1000,0,12,NaN
25,7505919,40,59,114,1000,2,8,NaN
26,7505919,41,85,199,1001,1,3,NaN
27,7505919,42,60,259,1001,1,0,NaN
28,7505919,43,84,343,1001,1,-2,NaN
29,7505919,44,0,343,999,1,0,NaN
30,6455623,4,50,50,1006,0,5,NaN
31,6455623,5,57,87,1008,6,13,NaN
32,6455623,6,70,157,1012,0,14,NaN
33,6455623,7,41,198,1014,2,4,NaN
34,6455623,8,37,235,1015,1,2,NaN
35,6455623,9,30,265,1018,1,0,NaN
36,6455623,10,32,297,1017,0,-1,NaN
37,6455623,11,62,359,1014,0,0,NaN
38,6455623,12,44,403,1008,0,0,NaN
39,6455623,13,68,471,1002,0,0,NaN
40,6455623,14,34,505,999,0,1,NaN
41,6455623,15,42,547,999,0,0,NaN
42,6455623,16,48,595,999,0,0,NaN
43,6455623,17,67,662,1002,0,7,NaN
44,6455623,18,35,697,1007,0,1,NaN
45,6455623,19,53,750,1005,0,0,NaN
46,6455623,20,42,792,1003,0,0,NaN
47,6455623,21,39,831,1004,0,-1,NaN
48,6455623,22,53,884,1005,0,0,NaN
49,6455623,23,46,930,1002,1,1,NaN
50,6455623,24,60,990,1001,0,1,NaN
51,6455623,25,41,1031,1001,0,0,0.0
52,6455623,26,59,1090,1002,0,0,0.0
53,6455623,27,64,1154,997,0,1,0.0
54,6455623,28,36,1190,999,0,0,0.0
55,6455623,29,58,1248,1001,0,2,0.0
56,6455623,30,0,1248,1001,0,0,0.0
57,6455623,31,0,1248,1001,0,0,0.0
58,6455623,32,0,1248,1004,0,0,0.0
59,6455623,33,0,1248,1006,0,0,0.0
60,6455623,34,0,1248,1006,0,0,0.0
61,6455623,35,0,1248,1006,0,0,0.0
62,6455623,36,0,1248,1006,0,0,0.0
63,6455623,37,0,1248,1006,0,0,0.0
64,6455623,38,0,1248,1006,0,0,0.0
65,6455623,39,66,1314,990,26,2,0.0
66,6455623,40,74,1388,992,1,3,0.0
67,6455623,41,56,1444,994,1,7,0.0
68,6455623,42,75,1515,994,2,3,0.0
69,6455623,43,69,1584,995,1,0,0.0
70,6455623,44,0,1584,994,2,0,0.0
71,7496007,39,92,92,1000,0,8,NaN
72,7496007,40,56,148,1002,1,-1,NaN
73,7496007,41,61,209,1004,1,3,NaN
74,7496007,42,54,259,1008,2,7,NaN
75,7496007,43,70,329,1011,1,-1,NaN
76,7496007,44,0,329,1011,3,0,NaN
77,7495061,39,56,56,1000,0,9,NaN
78,7495061,40,73,125,1002,2,2,NaN
79,7495061,41,98,223,1007,1,3,NaN
80,7495061,42,54,277,1011,1,7,NaN
81,7495061,43,54,327,1015,2,2,NaN
82,7495061,44,0,327,1015,5,0,NaN
83,6455571,4,59,59,1002,0,5,NaN
84,6455571,5,61,100,1008,6,6,NaN
85,6455571,6,65,165,1010,0,5,NaN
86,6455571,7,44,209,1013,2,6,NaN
87,6455571,8,43,252,1013,1,6,NaN
88,6455571,9,29,281,1015,1,8,NaN
89,6455571,10,46,327,1014,0,7,NaN
90,6455571,11,60,387,1015,0,9,NaN
91,6455571,12,55,442,1014,0,1,NaN
92,6455571,13,54,496,1013,0,0,NaN
93,6455571,14,75,571,1010,0,0,NaN
94,6455571,15,52,623,1010,0,9,NaN
95,6455571,16,61,684,1013,0,2,NaN
96,6455571,17,57,741,1013,0,0,NaN
97,6455571,18,22,763,1011,0,0,NaN
98,6455571,19,54,817,1008,0,0,NaN
99,6455571,20,47,864,1006,0,0,NaN
100,6455571,21,47,911,1005,0,1,NaN
101,6455571,22,41,952,1006,0,0,NaN
102,6455571,23,57,1009,1003,0,1,0.0
103,6455571,24,73,1082,1004,0,0,0.0
104,6455571,25,58,1140,1003,0,9,0.0
105,6455571,26,58,1198,1008,0,2,0.0
106,6455571,27,77,1275,1008,0,0,0.0
107,6455571,28,32,1307,1008,0,0,0.0
108,6455571,29,41,1348,1008,0,0,0.0
109,6455571,30,0,1348,1009,0,0,0.0
110,6455571,31,0,1348,1009,0,0,0.0
111,6455571,32,0,1348,1008,0,0,0.0
112,6455571,33,0,1348,1009,0,0,0.0
113,6455571,34,0,1348,1009,0,0,0.0
114,6455571,35,0,1348,1009,0,0,0.0
115,6455571,36,0,1348,1009,0,0,0.0
116,6455571,37,0,1348,1009,0,0,0.0
117,6455571,38,0,1348,1009,0,0,0.0
118,6455571,39,64,1412,1000,24,1,0.0
119,6455571,40,53,1461,1001,2,3,0.0
120,6455571,41,77,1538,1003,1,9,0.0
121,6455571,42,63,1593,1005,3,4,0.0
122,6455571,43,81,1666,1006,3,0,0.0
123,6455571,44,0,1666,1007,2,0,0.0
124,6455293,4,52,52,1004,0,6,NaN
125,6455293,5,40,52,1007,11,3,NaN
126,6455293,6,75,127,1008,0,4,NaN
127,6455293,7,50,177,1010,1,4,NaN
128,6455293,8,39,216,1011,2,5,NaN
129,6455293,9,30,246,1014,0,9,NaN
130,6455293,10,33,279,1014,0,0,NaN
131,6455293,11,63,342,1011,0,0,NaN
132,6455293,12,47,389,1010,0,0,NaN
133,6455293,13,50,439,1009,0,0,NaN
134,6455293,14,74,513,1004,0,8,NaN
135,6455293,15,55,568,1009,0,2,NaN
136,6455293,16,53,621,1018,0,0,NaN
137,6455293,17,65,686,1020,0,0,NaN
138,6455293,18,56,738,1019,3,0,NaN
139,6455293,19,35,765,1019,3,2,NaN
140,6455293,20,65,830,1021,0,0,NaN
141,6455293,21,54,864,1021,7,5,NaN
142,6455293,22,56,920,1023,0,6,NaN
143,6455293,23,30,950,1029,0,15,NaN
144,6455293,24,42,992,1029,2,7,NaN
145,6455293,25,37,1029,1030,0,0,0.0
146,6455293,26,63,1092,1028,2,8,0.0
147,6455293,27,61,1153,1027,0,2,0.0
148,6455293,28,24,1177,1027,0,0,0.0
149,6455293,29,66,1243,1024,0,1,0.0
150,6455293,30,0,1243,1021,0,0,0.0
151,6455293,31,0,1243,1021,0,0,0.0
152,6455293,32,0,1243,1019,0,0,0.0
153,6455293,33,0,1243,1021,0,0,0.0
154,6455293,34,0,1243,1021,0,0,0.0
155,6455293,35,0,1243,1021,0,0,0.0
156,6455293,36,0,1243,1021,0,0,0.0
157,6455293,37,0,1243,1021,0,0,0.0
158,6455293,38,0,1243,1021,0,0,0.0
159,6455293,39,77,1320,1003,21,2,0.0
160,6455293,40,74,1394,1004,1,2,0.0
161,6455293,41,53,1447,1008,1,3,0.0
162,6455293,42,46,1489,1009,2,2,0.0
163,6455293,43,62,1547,1012,2,0,0.0
164,6455293,44,0,1547,1012,1,0,0.0
165,7506788,39,61,61,1000,0,1,NaN
166,7506788,40,60,113,1002,3,4,NaN
167,7506788,41,49,162,1004,1,7,NaN
168,7506788,42,70,228,1004,2,4,NaN
169,7506788,43,82,302,1006,3,2,NaN
170,7506788,44,0,302,1009,1,0,NaN
171,7495692,39,73,73,1000,0,10,NaN
172,7495692,40,75,148,1002,1,9,NaN
173,7495692,41,36,184,1005,1,3,NaN
174,7495692,42,60,240,1006,2,2,NaN
175,7495692,43,55,291,1009,2,1,NaN
176,7495692,44,0,291,1010,3,0,NaN
177,6455462,4,52,52,1003,0,0,NaN
178,6455462,5,40,84,1005,3,11,NaN
179,6455462,6,76,160,1008,0,0,NaN
180,6455462,7,49,209,1010,2,6,NaN
181,6455462,8,32,237,1014,2,9,NaN
182,6455462,9,29,266,1015,0,11,NaN
183,6455462,10,46,312,1015,0,1,NaN
184,6455462,11,33,345,1012,0,7,NaN
185,6455462,12,41,386,1009,0,2,NaN
186,6455462,13,61,447,1006,0,10,NaN
187,6455462,14,55,502,1007,0,1,NaN
188,6455462,15,73,575,1010,0,20,NaN
189,6455462,16,72,647,1019,0,2,NaN
190,6455462,17,65,712,1022,0,7,NaN
191,6455462,18,64,776,1026,0,3,NaN
192,6455462,19,28,804,1026,0,2,NaN
193,6455462,20,56,860,1026,0,0,NaN
194,6455462,21,61,905,1024,6,1,NaN
195,6455462,22,55,960,1025,0,4,NaN
196,6455462,23,30,990,1031,0,13,NaN
197,6455462,24,33,1023,1031,0,11,0.0
198,6455462,25,27,1050,1028,0,0,0.0
199,6455462,26,64,1114,1025,0,2,0.0
200,6455462,27,51,1165,1022,0,1,0.0
201,6455462,28,18,1183,1023,0,0,0.0
202,6455462,29,78,1261,1021,0,0,0.0
203,6455462,30,0,1261,1018,0,0,0.0
204,6455462,31,0,1261,1018,0,0,0.0
205,6455462,32,0,1261,1018,0,0,0.0
206,6455462,33,0,1261,1018,0,0,0.0
207,6455462,34,0,1261,1018,0,0,0.0
208,6455462,35,0,1261,1018,0,0,0.0
209,6455462,36,0,1261,1018,0,0,0.0
210,6455462,37,0,1261,1018,0,0,0.0
211,6455462,38,0,1261,1018,0,0,0.0
212,6455462,39,55,1316,1009,7,2,0.0
213,6455462,40,66,1382,1004,1,8,0.0
214,6455462,41,55,1437,1005,1,2,0.0
215,6455462,42,61,1494,1006,2,17,0.0
216,6455462,43,60,1550,1010,2,19,0.0
217,6455462,44,0,1550,1009,3,0,0.0

In [38]:
# frioMurteira = data.loc[(data["POM"] == "Murteira") & (data["TMP"] > 7.2), ["DTM","TMP"]]
player_name = data['player_name'].tolist()
names = []
# print(player_name)

for name in player_name:
#     print(name)
    for team in team_id:
        name = player_df.loc[player_df['Team ID'] == team]
        names.append(name)
type(names)

list

In [37]:
pd.DataFrame(names,columns= ['Team ID','GW', 'Points','Total Points','Sqaud Value', 'Transfers in GW', 'Points on Bench']).set_index('Team ID')

ValueError: Shape of passed values is (169, 1), indices imply (169, 7)

In [36]:
type(names)

list

In [33]:

# data=[['Australia',100],['France',200],['Germany',300],['America',400]]
# pd.DataFrame(data,columns=columns= ['Team ID','GW', 'Points','Total Points','Sqaud Value', 'Transfers in GW', 'Points on Bench']).set_index('Team ID') 

# Out[2]:
#            Volume
# Country          
# Australia     100
# France        200
# Germany       300
# America       400

In [30]:
# frioMurteira = data.loc[(data["POM"] == "Murteira") & (data["TMP"] > 7.2), ["DTM","TMP"]]
p1 = player_df.loc[(player_df["Team ID"] ==  )]
# team_id = data['entry'].tolist()

# player_name = data['player_name'].tolist()
# d = {}
# for name in player_name:
#     d[name] = pd.DataFrame()

In [31]:
p1

Empty DataFrame
Columns: [Team ID, GW, Points, Total Points, Sqaud Value, Transfers in GW, Points on Bench]
Index: []

In [14]:
# numb_range = My_list = [*range(0, 13, 1)] 

# for i in range(13):
#     print(i)
#     i =pd.DataFrame(names[i])





# cols = ["G", "GA", "xG", "xGA", "GD", "xGD", "npxG", "npxGA","npxGD"]

# for col in cols:
#     teams_table['%s_pg' % col] = teams_table[col].div(teams_table['Games'], axis =0)
# munt = munt[munt['event']>=39]
# munt

In [21]:
data_p ={}
data_tp = pd.DataFrame()
all_dataframes = []

for i in range(len(data['entry'])):
    p_name = str(data['player_name'][i]) + "="
    url_only = 'https://fantasy.premierleague.com/api/entry/' + str(data['entry'][i]) + '/history/'
    p_name_url = p_name + url_only
    p = requests.get(url_only).text
    json_data_p = json.loads(p)
#     print(json.dumps(json_data_p, indent =2))  #prints JSON for every player
        
        

    
    #dictionary
    data_p[data['player_name'][i]] = json_data_p['current']
#     print(data_p)
    
    
    #converting dict to pd DF
    data_p[data['player_name'][i]] = pd.DataFrame(json_data_p['current'], columns=["total_points"])
    all_dataframes.append(data_p[data['player_name'][i]])
    
#     #alternate way
#     data_tp[data['player_name'][i]] = pd.DataFrame(json_data_p["current"], columns=["total_points"])
#     all_dataframes.append(data_tp[data['player_name'][i]])
    
    #csv
#     data_p[data['player_name'][i]].to_csv('player_' + str(data['player_name'][i])+ '.csv',index = True)
    

    
#     aw2
#     data_tp1['%s' %data['player_name'][i]] = pd.DataFrame(json_data["current"], columns=["total_points"])

In [24]:
all_dataframes

[   total_points
 0            95
 1           164
 2           260
 3           311
 4           371
 5           371,    total_points
 0            61
 1           124
 2           187
 3           259
 4           357
 5           357,    total_points
 0            69
 1           137
 2           230
 3           286
 4           347
 5           347,    total_points
 0            72
 1           135
 2           220
 3           288
 4           346
 5           346,    total_points
 0            59
 1           114
 2           199
 3           259
 4           343
 5           343,     total_points
 0             50
 1             87
 2            157
 3            198
 4            235
 5            265
 6            297
 7            359
 8            403
 9            471
 10           505
 11           547
 12           595
 13           662
 14           697
 15           750
 16           792
 17           831
 18           884
 19           930
 20           990
 21          1031
 22          1090
 23          1154
 24          1190
 25          1248
 26          1248
 27          1248
 28          1248
 29          1248
 30          1248
 31          1248
 32          1248
 33          1248
 34          1248
 35          1314
 36          1388
 37          1444
 38          1515
 39          1584
 40          1584,    total_points
 0            92
 1           148
 2           209
 3           259
 4           329
 5           329,    total_points
 0            56
 1           125
 2           223
 3           277
 4           327
 5           327,     total_points
 0             59
 1            100
 2            165
 3            209
 4            252
 5            281
 6            327
 7            387
 8            442
 9            496
 10           571
 11           623
 12           684
 13           741
 14           763
 15           817
 16           864
 17           911
 18           952
 19          1009
 20          1082
 21          1140
 22          1198
 23          1275
 24          1307
 25          1348
 26          1348
 27          1348
 28          1348
 29          1348
 30          1348
 31          1348
 32          1348
 33          1348
 34          1348
 35          1412
 36          1461
 37          1538
 38          1593
 39          1666
 40          1666,     total_points
 0             52
 1             52
 2            127
 3            177
 4            216
 5            246
 6            279
 7            342
 8            389
 9            439
 10           513
 11           568
 12           621
 13           686
 14           738
 15           765
 16           830
 17           864
 18           920
 19           950
 20           992
 21          1029
 22          1092
 23          1153
 24          1177
 25          1243
 26          1243
 27          1243
 28          1243
 29          1243
 30          1243
 31          1243
 32          1243
 33          1243
 34          1243
 35          1320
 36          1394
 37          1447
 38          1489
 39          1547
 40          1547,    total_points
 0            61
 1           113
 2           162
 3           228
 4           302
 5           302,    total_points
 0            73
 1           148
 2           184
 3           240
 4           291
 5           291,     total_points
 0             52
 1             84
 2            160
 3            209
 4            237
 5            266
 6            312
 7            345
 8            386
 9            447
 10           502
 11           575
 12           647
 13           712
 14           776
 15           804
 16           860
 17           905
 18           960
 19           990
 20          1023
 21          1050
 22          1114
 23          1165
 24          1183
 25          1261
 26          1261
 27          1261
 28          1261
 29          1261
 30          1261
 31          1261
 32          1261
 33          1261
 34          1261
 35          1316
 36          1382
 37          1437
 38          1494
 39          1550
 40          1550]

In [ ]:
# print(all_dataframes)

In [ ]:
 all_dataframes

In [ ]:
# data_tp

In [ ]:
munt = pd.read_csv(r'C:\Users\Asus\PycharmProjects\FPL Mini League Standings Visualization\player_Muntasir Azad.csv')
# data_df_f= data_p[data_p['Muntasir Azad']['event'] >= 39]

In [ ]:
munt = munt[munt['event']>=39]
munt

In [ ]:
munt['total_points'].iloc[0]

In [ ]:
munt['total_points'].iloc[0] =  0
munt

In [ ]:
# munt[munt['total_points'].iloc  == 0]
# munt[munt['total_points'].iloc[0]] == munt[munt['points'].iloc[0]]
# munt


# munt['total_points'][munt['total_points'].iloc == 0] = munt['points'][0]
# df['LastName'][df.ID == 103] = "Jones"


# len(munt['total_points'])
for i in range(len(munt['total_points'])):
    print(munt['total_points'].iloc[i-1])
    munt['total_points'].iloc[i] = munt['total_points'].iloc[i-1] + munt['points'].iloc[i]

In [ ]:
munt